name: Build project

on: 
  pull_request: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE}}

jobs:
  buildForSomePlatform:
    name: Build for ${{ matrix.targetPlatform}} on version ${{matrix.unityVersion}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - TeamBuildingAR
        unityVersion:
          - 2019.3.1f1
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
