name: Build project

on: 
  pull_request: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE}}

jobs:
  build:
    name: Build unity project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.2.11f1
