name: "Add testplan to body of pr"
on: pull_request

jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-regex: '*'
          body-template: 'Reviwers should check if pr follows [test plan](https://docs.google.com/document/d/1sL6BVXYbDczIXVd3Xx2QLMYn3e3Ft4zQhiHg4bF8n_A/edit?usp=sharing)'
          body-prefix-newline-count: 2
